// Part 3 of Perfume Database Extension (117 to 150) plus concatenation and exports
const FRAGRANCE_DB_3 = [
  { id: "p117", brand: "Maison Crivelli", name: "Hibiscus Mahajád", fragId: "64527", family: "floral", icon: "🌺", description: "Burning, leathery hibiscus with mint and vanilla.", notes: "Hibiscus · Mint · Vanilla", scores: { floral: 9, oriental: 6, woody: 3, fresh: 4, chypre: 3, fougere: 2 } },
  { id: "p118", brand: "Escentric Molecules", name: "Molecule 01", fragId: "845", family: "woody", icon: "🔬", description: "Pure Iso E Super. A radiant, transparent cedar wood.", notes: "Iso E Super", scores: { floral: 2, oriental: 2, woody: 10, fresh: 6, chypre: 3, fougere: 4 } },
  { id: "p119", brand: "Kilian", name: "Black Phantom", fragId: "43632", family: "oriental", icon: "💀", description: "Gourmand memento mori. Rum, coffee, cyanide, and sugar cane.", notes: "Rum · Dark Chocolate · Coffee", scores: { floral: 1, oriental: 10, woody: 6, fresh: 1, chypre: 2, fougere: 2 } },
  { id: "p120", brand: "Yves Saint Laurent", name: "La Nuit de L'Homme", fragId: "5521", family: "woody", icon: "🌃", description: "Suave cardamom and lavender. Parisian seduction par excellence.", notes: "Cardamom · Lavender · Cedar", scores: { floral: 3, oriental: 6, woody: 8, fresh: 4, chypre: 3, fougere: 6 } },
  { id: "p121", brand: "Mugler", name: "Alien Goddess", fragId: "69404", family: "oriental", icon: "🌞", description: "Solar gold infused with Bourbon vanilla and divine jasmine.", notes: "Coconut Water · Jasmine · Vanilla", scores: { floral: 6, oriental: 8, woody: 2, fresh: 4, chypre: 1, fougere: 1 } },
  { id: "p122", brand: "Giorgio Armani", name: "My Way Intense", fragId: "72798", family: "floral", icon: "🌸", description: "An overdosed tuberose resting on warm woods.", notes: "Orange Blossom · Tuberose · Sandalwood", scores: { floral: 10, oriental: 4, woody: 5, fresh: 2, chypre: 1, fougere: 1 } },
  { id: "p123", brand: "Paco Rabanne", name: "Lady Million", fragId: "13048", family: "floral", icon: "💎", description: "Opulent white flowers and notes of carnal honey.", notes: "Neroli · Jasmine · Honey", scores: { floral: 8, oriental: 5, woody: 3, fresh: 4, chypre: 3, fougere: 1 } },
  { id: "p124", brand: "Viktor&Rolf", name: "Spicebomb", fragId: "13857", family: "oriental", icon: "💣", description: "An explosion of hot and cold spices: pepper, cinnamon, saffron.", notes: "Pink Pepper · Cinnamon · Tobacco", scores: { floral: 1, oriental: 9, woody: 7, fresh: 2, chypre: 2, fougere: 4 } },
  { id: "p125", brand: "Guerlain", name: "Bois d'Arménie", fragId: "35892", family: "woody", icon: "📄", description: "Papier d'Arménie reinvented. Incense, benzoin, and delicate woods.", notes: "Incense · Iris · Benzoin", scores: { floral: 3, oriental: 8, woody: 9, fresh: 1, chypre: 4, fougere: 2 } },
  { id: "p126", brand: "Celine", name: "Black Tie", fragId: "65041", family: "oriental", icon: "🕴️", description: "Dry vanilla, orris root, and musk. Nocturnal couture elegance.", notes: "Iris Butter · Cedar · Vanilla", scores: { floral: 4, oriental: 8, woody: 7, fresh: 2, chypre: 3, fougere: 3 } },
  { id: "p127", brand: "Tom Ford", name: "Tuscan Leather", fragId: "10174", family: "woody", icon: "🚗", description: "Supreme leather rubbed with jammy raspberry.", notes: "Raspberry · Leather · Suede", scores: { floral: 2, oriental: 4, woody: 10, fresh: 1, chypre: 6, fougere: 2 } },
  { id: "p128", brand: "Tom Ford", name: "Neroli Portofino", fragId: "14354", family: "fresh", icon: "🚤", description: "The Italian Riviera, soapy neroli, and white flowers.", notes: "Bergamot · Neroli · Orange Blossom", scores: { floral: 5, oriental: 1, woody: 2, fresh: 10, chypre: 2, fougere: 4 } },
  { id: "p129", brand: "Acqua di Parma", name: "Fico di Amalfi", fragId: "14348", family: "fresh", icon: "🍋", description: "Fig nectar from the Amalfi Coast under the summer sun.", notes: "Grapefruit · Fig Nectar · Cedar", scores: { floral: 3, oriental: 2, woody: 5, fresh: 10, chypre: 2, fougere: 2 } },
  { id: "p130", brand: "Baccarat", name: "Baccarat Rouge 540 Extrait", fragId: "52997", family: "oriental", icon: "♦️", description: "Red intensified. Bitter almond, saffron, and powerful ambergris.", notes: "Almond · Saffron · Ambergris", scores: { floral: 4, oriental: 10, woody: 6, fresh: 1, chypre: 3, fougere: 3 } },
  { id: "p131", brand: "Clive Christian", name: "No. 1 for Men", fragId: "1614", family: "oriental", icon: "👑", description: "Formerly the most expensive perfume in the world. Grandiose iris and ylang.", notes: "Grapefruit · Ylang-Ylang · Sandalwood", scores: { floral: 6, oriental: 8, woody: 8, fresh: 4, chypre: 5, fougere: 3 } },
  { id: "p132", brand: "Xerjoff", name: "Alexandria II", fragId: "29189", family: "woody", icon: "🏛️", description: "Lavender, apple, and the purest, most precious Laotian oud.", notes: "Rosewood · Lavender · Oud", scores: { floral: 5, oriental: 8, woody: 9, fresh: 2, chypre: 4, fougere: 6 } },
  { id: "p133", brand: "Stephane Humbert Lucas", name: "Mortal Skin", fragId: "51148", family: "woody", icon: "🐍", description: "The spell of the serpent. Blackberry, ink, incense, and wood.", notes: "Blackberry · Ink · Myrrh", scores: { floral: 2, oriental: 7, woody: 8, fresh: 2, chypre: 5, fougere: 2 } },
  { id: "p134", brand: "Tiziana Terenzi", name: "Kirke", fragId: "40087", family: "floral", icon: "🍑", description: "Passion fruit, peach, and warm sand. Exotic and high-performing.", notes: "Passion Fruit · Peach · Musk", scores: { floral: 6, oriental: 3, woody: 3, fresh: 8, chypre: 4, fougere: 1 } },
  { id: "p135", brand: "Creed", name: "Virgin Island Water", fragId: "7682", family: "fresh", icon: "🥥", description: "The Caribbean in a bottle. Lime, fresh coconut, and white rum.", notes: "Lime · Coconut · Rum", scores: { floral: 3, oriental: 3, woody: 2, fresh: 10, chypre: 1, fougere: 2 } },
  { id: "p136", brand: "Parfums de Marly", name: "Pegasus", fragId: "38826", family: "oriental", icon: "🐎", description: "Metallic almond and elegant vanilla. Extreme refinement.", notes: "Almond · Vanilla · Sandalwood", scores: { floral: 3, oriental: 9, woody: 6, fresh: 2, chypre: 2, fougere: 4 } },
  { id: "p137", brand: "Maison Francis Kurkdjian", name: "Oud Satin Mood", fragId: "45292", family: "oriental", icon: "🌹", description: "The softness of silk. Bulgarian rose drowned in a base of vanilla and oud.", notes: "Bulgarian Rose · Oud · Vanilla", scores: { floral: 9, oriental: 9, woody: 8, fresh: 1, chypre: 3, fougere: 1 } },
  { id: "p138", brand: "Memo Paris", name: "African Leather", fragId: "27082", family: "woody", icon: "🦓", description: "A botanical safari, pure leather, and burning cardamom.", notes: "Cardamom · Leather · Vetiver", scores: { floral: 2, oriental: 7, woody: 9, fresh: 4, chypre: 5, fougere: 3 } },
  { id: "p139", brand: "Memo Paris", name: "Marfa", fragId: "44371", family: "floral", icon: "🏜️", description: "The eye of Texas. Hypnotic tuberose gorged with agave and vanilla.", notes: "Agave · Tuberose · Vanilla", scores: { floral: 10, oriental: 5, woody: 3, fresh: 3, chypre: 2, fougere: 1 } },
  { id: "p140", brand: "Bvlgari", name: "Tygar", fragId: "75842", family: "fresh", icon: "🐯", description: "The noblest sparkling ginger meets incandescent ambroxan.", notes: "Grapefruit · Ginger · Ambroxan", scores: { floral: 1, oriental: 3, woody: 7, fresh: 10, chypre: 3, fougere: 3 } },
  { id: "p141", brand: "Chanel", name: "Coromandel", fragId: "9068", family: "woody", icon: "🍱", description: "Thoroughbred patchouli, white chocolate, and incense. Coco's lacquered screens.", notes: "Bitter Orange · Patchouli · Incense", scores: { floral: 4, oriental: 8, woody: 9, fresh: 2, chypre: 7, fougere: 2 } },
  { id: "p142", brand: "Chanel", name: "Sycomore", fragId: "9071", family: "woody", icon: "🍂", description: "Vetiver of the highest quality, deeply rooted, dry, and noble.", notes: "Vetiver · Tobacco · Sandalwood", scores: { floral: 2, oriental: 3, woody: 10, fresh: 4, chypre: 6, fougere: 4 } },
  { id: "p143", brand: "Dior", name: "Ambre Nuit", fragId: "17537", family: "oriental", icon: "🌉", description: "The meeting of a delicate rose and an animalic ambergris.", notes: "Bergamot · Turkish Rose · Ambergris", scores: { floral: 7, oriental: 9, woody: 5, fresh: 3, chypre: 4, fougere: 2 } },
  { id: "p144", brand: "Dior", name: "Gris Dior", fragId: "59817", family: "chypre", icon: "🩶", description: "Couture gray. A contemporary chypre blending bergamot, rose, and oakmoss.", notes: "Bergamot · Rose · Oakmoss", scores: { floral: 8, oriental: 3, woody: 6, fresh: 5, chypre: 10, fougere: 3 } },
  { id: "p145", brand: "Amouage", name: "Jubilation XXV", fragId: "5902", family: "woody", icon: "👑", description: "Blackberry, olibanum, opoponax. A royal Omani celebration.", notes: "Blackberry · Honey · Olibanum", scores: { floral: 4, oriental: 8, woody: 9, fresh: 3, chypre: 7, fougere: 3 } },
  { id: "p146", brand: "Amouage", name: "Dia Woman", fragId: "908", family: "floral", icon: "🌸", description: "Soapy, aldehydic, noble fig. Elegant daytime radiance.", notes: "Aldehydes · Peony · White Musk", scores: { floral: 8, oriental: 3, woody: 4, fresh: 6, chypre: 5, fougere: 2 } },
  { id: "p147", brand: "Creed", name: "Royal Oud", fragId: "20578", family: "woody", icon: "🏛️", description: "The marble palace. Lemon, Lebanese cedar wood, and subtle oud.", notes: "Lemon · Angelica · Cedar", scores: { floral: 2, oriental: 4, woody: 9, fresh: 5, chypre: 4, fougere: 5 } },
  { id: "p148", brand: "Parfums de Marly", name: "Herod", fragId: "38823", family: "oriental", icon: "🚬", description: "Vanilla-infused tobacco, warm spices. Majestic and comforting.", notes: "Cinnamon · Tobacco · Vanilla", scores: { floral: 2, oriental: 9, woody: 6, fresh: 1, chypre: 2, fougere: 2 } },
  { id: "p149", brand: "Roja Parfums", name: "Danger Pour Homme", fragId: "20440", family: "oriental", icon: "⚠️", description: "Ambergris, lavender, and cumin of absolute richness. An alpha scent.", notes: "Lavender · Cumin · Ambergris", scores: { floral: 4, oriental: 8, woody: 7, fresh: 3, chypre: 5, fougere: 7 } },
  { id: "p150", brand: "Widian", name: "London", fragId: "57991", family: "woody", icon: "🇬🇧", description: "Raspberry leather with a refined East-meets-West smoky veil.", notes: "Raspberry · Violet · Leather", scores: { floral: 4, oriental: 5, woody: 8, fresh: 2, chypre: 4, fougere: 2 } }
];

// Family metadata
const FAMILY_META = {
  floral: { label: "Floral", color: "#d4748f", icon: "🌸", desc: "Flowers, bouquets, romanticism" },
  oriental: { label: "Oriental", color: "#e0965a", icon: "🌙", desc: "Spices, vanilla, warmth" },
  woody: { label: "Woody", color: "#4ca8a0", icon: "🌲", desc: "Woods, oud, untamed nature" },
  fresh: { label: "Fresh", color: "#7ab87a", icon: "🌊", desc: "Citrus, aquatic, lightness" },
  chypre: { label: "Chypre", color: "#9b8ec4", icon: "🍃", desc: "Sophistication, complexity" },
  fougere: { label: "Fougère", color: "#c9a84c", icon: "🌿", desc: "Aromatic, classic masculine" }
};

// Merge all into one array
const FRAGRANCE_DB = [...FRAGRANCE_DB_1, ...FRAGRANCE_DB_2, ...FRAGRANCE_DB_3];
