// ============================================================
// SCENTQUIZ — Persistent Storage & History
// ============================================================

/**
 * Saves quiz results to local storage.
 * @param {Array} answers - User's selected options.
 * @param {Array} topMatches - The top matches generated by the algorithm.
 */
function saveQuizResults(answers, topMatches) {
    const resultData = {
        timestamp: new Date().getTime(),
        date: new Date().toLocaleDateString(),
        answers: answers,
        topMatches: topMatches
    };

    localStorage.setItem('scentQuiz_lastResult', JSON.stringify(resultData));
    console.log('✅ Quiz results saved to local storage.');
}

/**
 * Retrieves the last saved quiz results.
 * @returns {Object|null} The saved result data or null if none exists.
 */
function getLastQuizResults() {
    const data = localStorage.getItem('scentQuiz_lastResult');
    try {
        return data ? JSON.parse(data) : null;
    } catch (e) {
        console.error('Failed to parse saved results:', e);
        return null;
    }
}

/**
 * Checks if there are saved results and attempts to display them.
 */
function showLastResults() {
    const saved = getLastQuizResults();
    if (saved && saved.topMatches) {
        // We need to ensure the quiz UI is open first
        if (typeof openQuizOverlay === 'function') {
            openQuizOverlay();
        }
        
        // Use the global matchPerfumes and renderResults logic from quiz.js
        // If we want to show EXACTLY what was saved, we might need to modify renderResults
        // For now, we'll re-render based on the saved outcome if possible.
        if (typeof renderResults === 'function') {
            // Note: quiz.js's renderResults() uses the global 'answers' variable.
            // We should ideally pass data, but we'll adapt to how quiz.js works.
            if (window.answers) {
                window.answers = saved.answers;
                renderResults();
            } else {
                // Fallback: use the saved matches directly if renderResults was more flexible
                renderResults(); 
            }
        }
    } else {
        alert("No previous results found. Take the diagnostic first!");
    }
}